version: "3.6"
services:
  selenium-hub:
      image: selenium/hub
      container_name: selenium-hub
      ports:
          - "4444:4444"
  chrome:
      image: selenium/node-chrome
      shm_size: 2gb
      depends_on:
          - selenium-hub
      environment:
          - SE_EVENT_BUS_HOST=selenium-hub
          - SE_EVENT_BUS_PUBLISH_PORT=4442
          - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      ports:
          - "6900:5900"
  web:
    build: .
    volumes:
      - .:/app
    command: /wait-for-it.sh selenium-hub:4444 -- python scrape.py
    depends_on:
      - selenium-hub # Add this dependency
      - chrome
